### ISSUE TITLE
Авто решение заготовленных ответов

### ISSUE THREAD

**Issue by Vladislav875** [acuifex/lolz-autocontest#12]
Есть ли возможность сделать условно файл answer.json, и туда записывать вопрос, и ответ, если скрипт встретит там вопрос который есть в этом json файле - вставляет уже заготовленный ответ который будет там записан, в других случаях будет так же запрашивать ответ на капчу.
Т.к. сейчас почти все делают простые тексты, по типу 1+1, 2+2=
Я думаю это сэкономит много денег если делать это с большим количеством аккаунтов

**Comment by acuifex** [comment]
Прикольно а как это с рекапчей поможет

**Comment by acuifex** [comment]
Без ответа оно решать рекапчу не будет: https://github.com/acuifex/lolz-autocontest/blob/33f5380ee9c4f2a858f8b6d4180e7e315c7f36f5/main.py#L249-L256
Единственная проблема которая сейчас есть это неверные вопросы в базе.
Подобные решения с кешированием ответов максимум могут только разгрузить сервер с ответами и слегка ускорить решения. 
НО мы решаем по айди темы т.к. есть дауны которые пишут "2+2" с ответом 5, по этому кешировать ответы по айдишникам темы особо нету.
