### ISSUE TITLE
Unknown hash, please verify that nothing is wrong

### ISSUE THREAD

**Issue by Pelmeska** [acuifex/lolz-autocontest#15]
Какое-то время скрипт работал и потом начал выдавать эту ошибку, перезапуск скрипта не помогает, что делать?
https://i.imgur.com/RJUjqJY.png

**Comment by Pelmeska** [comment]
решил

**Comment by haghyx** [comment]
как решил?

**Comment by acuifex** [comment]
Вариант 1: починить самому
Вариант 2: выключить проверку: https://github.com/acuifex/lolz-autocontest/blob/bb9c7efc3d5e443d26f6bb829f8bf16885d0fd91/settings.example.json#L17
