### ISSUE TITLE
Как получить df_uid автоматически?

### ISSUE THREAD

**Issue by prtolem** [acuifex/lolz-autocontest#8]
Помогите

**Comment by acuifex** [comment]
При запросе без df_uid любой страницы тебе должно прийти задание
Фунцкия `checkforjsandfix` проверит есть ли задание и установит куку df_uid
после этого нужно повторить запрос к странице

**Comment by prtolem** [comment]
спасибо большое

**Comment by acuifex** [comment]
Не забудь поменять внутренние переменные на свои и передавать ему beautifulsoup

**Comment by prtolem** [comment]
получаеться в вашем коде df_uid это вот эта строчка? `value = cipher.decrypt(bytearray.fromhex(value_encrypted)).hex()`

**Comment by acuifex** [comment]
Задание заключается в том что бы расшифровать aes 128 CBC зашифрованный текст с помощью известного iv и ключа. Фунцкия вытаскивает этот зашифрованный текст, расшифровывает его и устанавливает df_uid куку на сессии на расшифрованную строку

**Comment by prtolem** [comment]
так в этой переменной df_uid расшифрованный хрнаиться?
