### ISSUE TITLE
Может кто наклепать solvers.py, который в любом розыгрыше будет отвечать ником автора темы

### ISSUE THREAD

**Issue by RealMreg** [acuifex/lolz-autocontest#9]
Может кто наклепать solvers.py, который в любом розыгрыше будет отвечать ником автора темы

И по возможности если бы не решенные розыгрыши данным методом заносило в чс и больше не открывало

**Comment by xMementoMori** [comment]
нет

**Comment by BFG14** [comment]
это костыль

**Comment by acuifex** [comment]
Подобная проблема была решена еще давно: https://github.com/acuifex/lolz-autocontest/commit/463132703872547ececf3f2eb7fc674fd29569a9
